{{- $name := .Values.aws.accessKeyId | required ".Values.aws.accessKeyId is required." -}}
{{- $name := .Values.aws.secretKey | required ".Values.aws.secretKey is required." -}}

---
apiVersion: v1
kind: Secret
metadata:
  name: iamsecret
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.aws.accessKeyId }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.aws.secretKey }}
  